version: "3"

services:
  crontabui:
    image: plantstudio/crontabui
    restart: unless-stopped
    ports:
      - "8888:8000"    
    volumes:
      - cron:/etc/crontabs
    links:
      - fastapi

  grafana:
    image: grafana/grafana:8.2.1
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning  
    depends_on: 
      - influxdb
    links:
      - influxdb
      - fastapi

  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb

  couchdb:
    image: treehouses/couchdb:2.3.0
    restart: unless-stopped
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password    
    ports:
      - "5984:5984"
    volumes:
      - couchdb:/opt/couchdb/data

  fastapi:
    build: fastapi
    restart: unless-stopped
    ports:
      - "80:80"
      - "88:88"
    links:
      - couchdb
      - influxdb
    depends_on:
      - couchdb
      - influxdb

  mosquitto:
    image: plantstudio/mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  paho:
    build: paho
    restart: unless-stopped
    depends_on:
      - mosquitto

  psconfig:
    build: psconfig
    ports:
      - "222:22"
    depends_on: 
      - fastapi
      - paho
      - couchdb
      - grafana


  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "8000:8000"
      - "9433:9433"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  cron:
  influxdb:
  couchdb:
  mosquitto_conf:
  mosquitto_data:
  mosquitto_log:
  portainer_data: