apiVersion: 1
  
datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  password:
  user:
  database: grow1
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
  secureJsonData:
    tlsCACert: ""
    tlsClientCert: ""
    tlsClientKey: ""
  editable: true